version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  win: circleci/windows@2.4.1
  slack: circleci/slack@4.4.2

executors:
  with-chrome-and-firefox:
    docker:
      - image: justanoterone/webkit-cypress-browser:0.0.3
    resource_class: medium+  

  pw-focal-development:
     docker: 
       - image: mcr.microsoft.com/playwright:v1.27.0-focal
     environment:
        NODE_ENV: development
 

# Set parameter here
parameters:
  safari_tests:
    type: boolean
    default: false
  fireFox_tests:
    type: boolean
    default: true
  parallel_tests:
    type: boolean
    default: true
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-tests:
    description: |
      Notify the status of the build & generate allure report 
    steps:
     - run:
           name: generate combined report
           when: always
           command: |
                  npx report:allure
      - store_artifacts:
                path: mochawesome-report          
      - slack/notify:
                 event: fail
                 template: basic_fail_1
      - slack/notify:
                  event: pass
                  template: basic_success_1 


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
all-tests-workflow: &all-tests-workflow
 jobs:
   # Setup
    - cypress/install:
        name: "Setup Linux"
        executor: with-chrome-and-firefox
        post-steps:
          - run:
              name: Print machine info ℹ️
              command: yarn cypress info    

 # Run all tests 
    - cypress/run:
        name: "Run test on chrome"
        executor: with-chrome-and-firefox
        browser: chrome
        command: npm run cy:run-chrome
        no-workspace: true
          # always store any test screenshots and videos
        store_artifacts: true
        group: API
        requires:
          - Setup Linux
        post-steps:
          - report-tests

    - cypress/run:
        name: "Run test on firefox"
        executor: with-chrome-and-firefox
        browser: firefox
        command: npm run cy:run-firefox
        no-workspace: true
          # always store any test screenshots and videos
        store_artifacts: true
        group: Firefox
        requires:
          - Setup Linux
        post-steps:
         - report-tests
      
    - cypress/run:
        name: "Run API tests"
        command: npm run cy:run-api
        no-workspace: true
          # always store any test screenshots and videos
        store_artifacts: true
        group: API
        requires:
          - Setup Linux
        post-steps:
         - report-tests 

webkit-workflow: &webkit-workflow
 jobs:
   # Setup
    - cypress/install:
        name: "Setup Linux"
        executor: pw-focal-development
        post-steps:
          - run:
              name: Print machine info ℹ️
              command: yarn cypress info

 # Run safari tests 
    - cypress/run:
        name: "Run safari tests"
        command: npm run cy:run-safari
        executor: pw-focal-development
        browser: webkit
        no-workspace: true
          # always store any test screenshots and videos
        store_artifacts: true
        group: Webkit
        requires:
          - Setup Linux
        post-steps:
         - report-tests     



workflows:
  linux_parallel_test:
    when: << pipeline.parameters.parallel_tests>>
    <<: *all-tests-workflow

  safari_tests:
    when: << pipeline.parameters.safari_tests>>
    <<: *webkit-workflow
    
  # scheduled tasks
  parallel_scheduled:
    triggers:
      - schedule:
          cron: "30 4 * * 1-5"
          filters:
            branches:
              only:
                - main
    <<:  *all-tests-workflow

  safari_scheduled:
    triggers:
      - schedule:
          cron: "15 4 * * 1-5"
          filters:
            branches:
              only:
                - main
    <<:  *webkit-workflow

